### ISSUE TITLE
  "DirectLine": "directline:3000" in appsettings.json is not used

### ISSUE THREAD

**Issue by mouhannadali** [humbertojaimes/microsoft-build-bot#1]
Hi, 
the  "DirectLine": "directline:3000" in appsettings.json is not used any where. Instead, it is hard-coded in Connector.cs -> GetConversationsWithHttpMessagesAsync line 102.
is there a reason for that ?

**Comment by humbertojaimes** [comment]
Hi @mouhannadali 

I forgot to remove that config. It was created for testing. 

I was trying to avoid change the Bot Framework core, sadly I didn't have enough time to achieve it, so at the end I used the hardcoded url. 

Thanks.

**Comment by mouhannadali** [comment]
Thank you very much for the fast replay and the nice work. I am closing the issue.
